version: "3.8"
services:
  mongodb:
    container_name: mongodb-m150
    image: mongo
    env_file: './dev/.env'
    # specify command or entrypoint should be okay
    # command: ["mongod", "--auth"]
    command: ["--auth"]
    volumes:
      - ./conf:/etc/mongo
      - ./mongodb/database:/data/db
      - ./logs:/var/log/mongodb/
      - ./scripts:/docker-entrypoint-initdb.d:ro
    ports:
      - 27020:27017
    restart: "no"