version: "3.8"
services:
  mongodb:
    container_name: mongodb-m150
    image: mongo
    env_file: './dev/.env'
    # specify command or entrypoint should be okay
    # command: ["mongod", "--auth"]
    entrypoint: ["mongod", "--auth", "--config", "/etc/mongo/mongod.conf"]
    volumes:
      - ./conf:/etc/mongo
      - ./mongodb/database:/data/db
      - ./logs:/var/log/mongodb/
    ports:
      - 27020:27017
    restart: "no"