version: "3.8"
services:
  mongodb:
    container_name: mongodb-m150
    image: mongo
    env_file: './dev/.env'
    # command: 
    #   - '--auth'
    #   - '--config'
    #   - '/etc/mongod.conf'
    command: ["mongod", "--auth"]
    volumes:
      - ./conf:/etc/mongo
      - ./mongodb/database:/data/db
      - ./logs:/var/log/mongodb/
    ports:
      - 27020:27017
    restart: "no"